#!/usr/bin/env bash

# watch code changes, trigger re-build, and kill process
while true; do
    go build -o _build/linear-tui ./cmd/linear-tui
    if [ $? -eq 0 ]; then
        pkill -f '_build/linear-tui'
    fi
    fswatch -1 -e ".*" -i "\\.go$" . || exit
done
